kernelsu-objs := ksu.o
kernelsu-objs += allowlist.o
kernelsu-objs += dynamic_manager.o
kernelsu-objs += app_profile.o
kernelsu-objs += apk_sign.o
kernelsu-objs += sucompat.o

kernelsu-objs += throne_tracker.o
kernelsu-objs += pkg_observer.o
kernelsu-objs += setuid_hook.o

ifeq ($(CONFIG_KSU_MANUAL_HOOK), y)
ifeq ($(shell test $(VERSION) -lt 6 || { test $(VERSION) -eq 6 && test $(PATCHLEVEL) -lt 8; } && echo y),y)
kernelsu-objs += lsm_hooks.o
endif
endif

kernelsu-objs += kernel_compat.o
kernelsu-objs += kernel_umount.o
kernelsu-objs += supercalls.o
kernelsu-objs += su_mount_ns.o
kernelsu-objs += feature.o
kernelsu-objs += throne_tracker.o
kernelsu-objs += ksud.o
kernelsu-objs += seccomp_cache.o
kernelsu-objs += file_wrapper.o
kernelsu-objs += sulog.o

kernelsu-objs += selinux/selinux.o
kernelsu-objs += selinux/sepolicy.o
kernelsu-objs += selinux/rules.o

ccflags-y += -Wno-implicit-function-declaration -Wno-strict-prototypes -Wno-int-conversion
ccflags-y += -Wno-declaration-after-statement -Wno-unused-function -Wno-unused-variable -Wno-missing-braces
ccflags-y += -Wno-int-to-pointer-cast -Wno-declaration-after-statement

ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(objtree)/security/selinux -include $(srctree)/include/uapi/asm-generic/errno.h

obj-$(CONFIG_KSU) += kernelsu.o

obj-$(CONFIG_KPM) += kpm/

REPO_OWNER := ReSukiSU
REPO_NAME := ReSukiSU
REPO_BRANCH := main
KSU_VERSION_API := 4.1.0

GIT_BIN := /usr/bin/env PATH="$$PATH":/usr/bin:/usr/local/bin git
CURL_BIN := /usr/bin/env PATH="$$PATH":/usr/bin:/usr/local/bin curl

ifeq ($(findstring $(srctree),$(src)),$(srctree))
  KSU_SRC := $(src)
else
  KSU_SRC := $(srctree)/$(src)
endif

LOCAL_GIT_EXISTS := $(shell test -e $(KSU_SRC)/../.git && echo 1 || echo 0)

ifeq ($(LOCAL_GIT_EXISTS),0)
$(error You should use $(REPO_NAME) as an git submodule instead of directly copy code)
endif

define get_ksu_version_full
v$1-$(shell cd $(KSU_SRC); $(GIT_BIN) rev-parse --short=8 HEAD)@ReSukiSU
endef

$(shell cd $(KSU_SRC); [ -f ../.git/shallow ] && $(GIT_BIN) fetch --unshallow)
KSU_LOCAL_VERSION := $(shell cd $(KSU_SRC); $(GIT_BIN) rev-list --count $(REPO_BRANCH))
KSU_VERSION := $(shell expr 30000 + $(KSU_LOCAL_VERSION) + 700)
KSU_VERSION_FULL := $(call get_ksu_version_full,$(KSU_VERSION_API))

$(info -- $(REPO_NAME) version code: $(KSU_VERSION))
$(info -- $(REPO_NAME) version name: $(KSU_VERSION_FULL))

ccflags-y += -DKSU_VERSION=$(KSU_VERSION)
ccflags-y += -DKSU_VERSION_FULL=\"$(KSU_VERSION_FULL)\"

ifeq ($(CONFIG_KSU_MULTI_MANAGER_SUPPORT), y)
$(info -- Supported Unofficial Manager: MKSU, RKSU, SukiSU-Ultra, ReSukiSU )
endif

ifeq ($(CONFIG_KSU_MANUAL_HOOK), y)
$(info -- $(REPO_NAME): using KSU_MANUAL_HOOK)
else ifeq ($(CONFIG_KSU_SUSFS), y)
$(info -- $(REPO_NAME): using SUSFS_INLINE_HOOK)
else
ccflags-y += -DKSU_TP_HOOK
KSU_TP_HOOK := y
$(info -- $(REPO_NAME): using KSU_TRACEPOINT_HOOK)
endif

KERNEL_VERSION := $(VERSION).$(PATCHLEVEL)
KERNEL_TYPE := Non-GKI
# Check for GKI 2.0 (5.10+ or 6.x+)
ifneq ($(shell test \( $(VERSION) -ge 5 -a $(PATCHLEVEL) -ge 10 \) -o $(VERSION) -ge 6; echo $$?),0)
# Check for GKI 1.0 (5.4)
ifeq ($(shell test $(VERSION)-$(PATCHLEVEL) = 5-4; echo $$?),0)
KERNEL_TYPE := GKI 1.0
endif
else
KERNEL_TYPE := GKI 2.0
endif
$(info -- KERNEL_VERSION: $(KERNEL_VERSION))
$(info -- KERNEL_TYPE: $(KERNEL_TYPE))

# Check if KPM is enabled
ifeq ($(CONFIG_KPM), y)
$(info -- KPM is enabled)
$(info -- WARNING, This feature is unstable!!! You are WARNED!!!)
else
$(info -- KPM is disabled)
endif

ifeq ($(KSU_TP_HOOK), y)
kernelsu-objs += syscall_hook_manager.o
kernelsu-objs += util.o
endif

# SELinux drivers check
ifeq ($(shell grep -q "current_sid(void)" $(srctree)/security/selinux/include/objsec.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: current_sid found)
ccflags-y += -DKSU_COMPAT_HAS_CURRENT_SID
endif
ifeq ($(shell grep -q "struct selinux_state " $(srctree)/security/selinux/include/security.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: selinux_state found)
ccflags-y += -DKSU_COMPAT_HAS_SELINUX_STATE
endif

# Handle optional backports
ifeq ($(shell grep -q "strncpy_from_user_nofault" $(srctree)/include/linux/uaccess.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: strncpy found)
ccflags-y += -DKSU_OPTIONAL_STRNCPY
endif

ifeq ($(shell grep -q "ssize_t kernel_read" $(srctree)/fs/read_write.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat: kernel_read found)
ccflags-y += -DKSU_OPTIONAL_KERNEL_READ
endif

ifeq ($(shell grep "ssize_t kernel_write" $(srctree)/fs/read_write.c | grep -q "const void" ; echo $$?),0)
$(info -- $(REPO_NAME)/compat: kernel_write found)
ccflags-y += -DKSU_OPTIONAL_KERNEL_WRITE
endif

ifeq ($(shell grep -q "int\s\+path_mount" $(srctree)/fs/namespace.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat: path_mount found)
ccflags-y += -DKSU_HAS_PATH_MOUNT
endif

ifeq ($(shell grep -q "int\s\+path_umount" $(srctree)/fs/namespace.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat: path_umount found)
ccflags-y += -DKSU_HAS_PATH_UMOUNT
endif

ifeq ($(shell grep -q "inode_security_struct\s\+\*selinux_inode" $(srctree)/security/selinux/include/objsec.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: selinux_inode found)
ccflags-y += -DKSU_OPTIONAL_SELINUX_INODE
endif

ifeq ($(shell grep -q "task_security_struct\s\+\*selinux_cred" $(srctree)/security/selinux/include/objsec.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: selinux_cred found)
ccflags-y += -DKSU_OPTIONAL_SELINUX_CRED
endif

# seccomp_types.h were added on 6.7
ifeq ($(shell grep -q "atomic_t\s\+filter_count" $(srctree)/include/linux/seccomp.h $(srctree)/include/linux/seccomp_types.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: seccomp_filter_count found)
ccflags-y += -DKSU_OPTIONAL_SECCOMP_FILTER_CNT
endif

# some old kernel backport this, let's check if put_seccomp_filter still exist
ifneq ($(shell grep -wq "put_seccomp_filter" $(srctree)/kernel/seccomp.c $(srctree)/include/linux/seccomp.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: put_seccomp_filter found)
ccflags-y += -DKSU_OPTIONAL_SECCOMP_FILTER_RELEASE
endif

ifeq ($(shell grep -q "security_inode_init_security_anon" $(srctree)/include/linux/security.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: security_inode_init_security_anon found)
ccflags-y += -DKSU_OPTIONAL_HAS_INIT_SEC_ANON
endif

ifeq ($(shell grep -q "anon_inode_getfd_secure" $(srctree)/fs/anon_inodes.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat: anon_inode_getfd_secure found)
ccflags-y += -DKSU_HAS_GETFD_SECURE
endif

ifeq ($(shell grep -A1 "^int vfs_getattr" $(srctree)/fs/stat.c | grep -q "query_flags"; echo $$?),0)
$(info -- $(REPO_NAME)/compat: vfs_getattr() found)
ccflags-y += -DKSU_HAS_NEW_VFS_GETATTR
endif

ifeq ($(shell grep -q "static inline struct inode \*file_inode" $(srctree)/include/linux/fs.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: file_inode() found)
ccflags-y += -DKSU_UL_HAS_FILE_INODE
endif

# Checks Samsung
ifeq ($(shell grep -q "CONFIG_KDP_CRED" $(srctree)/kernel/cred.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat/samsung: CONFIG_KDP_CRED found)
ccflags-y += -DSAMSUNG_UH_DRIVER_EXIST
endif

ifeq ($(shell grep -q "SEC_SELINUX_PORTING_COMMON" $(srctree)/security/selinux/avc.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat/samsung: SEC_SELINUX_PORTING_COMMON found)
ccflags-y += -DSAMSUNG_SELINUX_PORTING
endif

# Function proc_ops check
ifeq ($(shell grep -q "struct proc_ops " $(srctree)/include/linux/proc_fs.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: proc_ops found)
ccflags-y += -DKSU_COMPAT_HAS_PROC_OPS
endif

# Custom Signs
ifdef KSU_EXPECTED_SIZE
ccflags-y += -DEXPECTED_SIZE=$(KSU_EXPECTED_SIZE)
$(info -- Custom KernelSU Manager signature size: $(KSU_EXPECTED_SIZE))
endif

ifdef KSU_EXPECTED_HASH
ccflags-y += -DEXPECTED_HASH=\"$(KSU_EXPECTED_HASH)\"
$(info -- Custom KernelSU Manager signature hash: $(KSU_EXPECTED_HASH))
endif

ifdef KSU_MANAGER_PACKAGE
ccflags-y += -DKSU_MANAGER_PACKAGE=\"$(KSU_MANAGER_PACKAGE)\"
$(info -- KernelSU Manager package name: $(KSU_MANAGER_PACKAGE))
endif

## For susfs stuff ##
ifeq ($(CONFIG_KSU_SUSFS), y)
ifeq ($(shell test -e $(srctree)/fs/susfs.c; echo $$?),0)
$(eval SUSFS_VERSION=$(shell cat $(srctree)/include/linux/susfs.h | grep -E '^#define SUSFS_VERSION' | cut -d' ' -f3 | sed 's/"//g'))
$(info )
$(info -- SUSFS_VERSION: $(SUSFS_VERSION))
else
$(info -- You have not integrated susfs in your kernel yet.)
$(info -- Read: https://gitlab.com/simonpunk/susfs4ksu)
$(error You should integrate susfs in your kernel.)
endif
endif

## deny lkm build
ifeq ($(CONFIG_KSU), m)
$(error This branch not support LKM build, you should use main branch!)
endif

# manual hook check
ifeq ($(CONFIG_KSU_MANUAL_HOOK), y)

  ifeq ($(CONFIG_KSU_MANUAL_HOOK_AUTO_SETUID_HOOK), y)
    $(info -- $(REPO_NAME)/manual_hook: You are using LSM hooks for setuid hooks.)
    ifeq ($(VERSION),6)
      ifeq ($(shell test $(PATCHLEVEL) -ge 8 && echo y),y)
        $(info -- You can't use LSM hooks for kernel version higher than 6.8)
        $(info -- You should turn off CONFIG_KSU_MANUAL_HOOK_AUTO_SETUID_HOOK and manually setresuid hook)
        $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
        $(error You can't use LSM hooks when kernel version >= 6.8)
      endif
    endif
  else
    $(info -- $(REPO_NAME)/manual_hook: You are using manually setresuid hook for setuid hooks.)

    ifeq ($(shell grep -q "ksu_handle_setresuid" $(srctree)/kernel/sys.c; echo $$?),0)
      $(info -- $(REPO_NAME)/manual_hook: ksu_handle_setresuid found)
    else
      $(info -- You lost ksu_handle_setresuid hook in your kernel)
      $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
      $(error You should integrate $(REPO_NAME) in your kernel.)
    endif
  endif

  ifeq ($(CONFIG_KSU_MANUAL_HOOK_AUTO_INITRC_HOOK), y)
    $(info -- $(REPO_NAME)/manual_hook: You are using LSM hooks for init rc hooks.)
    ifeq ($(VERSION),6)
      ifeq ($(shell test $(PATCHLEVEL) -ge 8 && echo y),y)
        $(info -- You can't use LSM hooks for kernel version higher than 6.8)
        $(info -- You should turn off CONFIG_KSU_MANUAL_HOOK_AUTO_INITRC_HOOK and manually sys_read hook)
        $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
        $(error You can't use LSM hooks when kernel version >= 6.8)
      endif
    endif
  else
    $(info -- $(REPO_NAME)/manual_hook: You are using manually sys_read hook for init rc hooks.)

    ifeq ($(shell grep -q "ksu_handle_sys_read" $(srctree)/fs/read_write.c; echo $$?),0)
      $(info -- $(REPO_NAME)/manual_hook: ksu_handle_sys_read found)
    else
      $(info -- You lost ksu_handle_sys_read hook in your kernel)
      $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
      $(error You should integrate $(REPO_NAME) in your kernel.)
    endif
  endif

  ifeq ($(shell grep -q "ksu_vfs_read_hook" $(srctree)/fs/read_write.c; echo $$?),0)
    $(info -- ksu_vfs_read_hook is incompatible hook)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel correctly.)
  endif

  ifeq ($(CONFIG_KSU_MANUAL_HOOK_AUTO_INPUT_HOOK), y)
    $(info -- $(REPO_NAME)/manual_hook: You are using input_handler for input hooks.)
  else
    ifeq ($(shell grep -q "ksu_handle_input_handle_event" $(srctree)/drivers/input/input.c; echo $$?),0)
      $(info -- $(REPO_NAME)/manual_hook: ksu_handle_input_handle_event found)
    else
      $(info -- You lost ksu_handle_input_handle_event hook in your kernel)
      $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
      $(error You should integrate $(REPO_NAME) in your kernel.)
    endif
  endif

  ifeq ($(shell grep -q "ksu_handle_execveat" $(srctree)/fs/exec.c; echo $$?),0)
    $(info -- $(REPO_NAME)/manual_hook: ksu_handle_execveat found)
  else
    $(info -- You lost ksu_handle_execveat hook in your kernel)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel.)
  endif

  ifeq ($(shell grep -q "ksu_handle_faccessat" $(srctree)/fs/open.c; echo $$?),0)
    $(info -- $(REPO_NAME)/manual_hook: ksu_handle_faccessat found)
  else
    $(info -- You lost ksu_handle_faccessat hook in your kernel)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel.)
  endif

  ifeq ($(shell grep -q "ksu_handle_stat" $(srctree)/fs/stat.c; echo $$?),0)
    $(info -- $(REPO_NAME)/manual_hook: ksu_handle_stat found)
  else
    $(info -- You lost ksu_handle_stat hook in your kernel)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel.)
  endif

  ifeq ($(shell grep -q "ksu_handle_newfstat_ret" $(srctree)/fs/stat.c; echo $$?),0)
    $(info -- $(REPO_NAME)/manual_hook: ksu_handle_newfstat_ret found)
  else
    $(info -- You lost ksu_handle_newfstat_ret hook in your kernel)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel.)
  endif 

  ifeq ($(shell grep -q "ksu_handle_fstat64_ret" $(srctree)/fs/stat.c; echo $$?),0)
    $(info -- $(REPO_NAME)/manual_hook: ksu_handle_fstat64_ret found)
  else
    $(info -- You lost ksu_handle_fstat64_ret hook in your kernel)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel.)
  endif

  ifeq ($(shell grep -q "ksu_handle_sys_reboot" $(srctree)/kernel/reboot.c; echo $$?),0)
    $(info -- $(REPO_NAME)/manual_hook: ksu_handle_sys_reboot found)
  else
    $(info -- You lost ksu_handle_sys_reboot hook in your kernel)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel.)
  endif

  ifeq ($(shell test $(VERSION) -lt 4 || { test $(VERSION) -eq 4 && test $(PATCHLEVEL) -lt 10; } && echo y),y)
    ifeq ($(shell grep -q "is_ksu_transition" $(srctree)/security/selinux/hooks.c; echo $$?),0)
      $(info -- $(REPO_NAME)/manual_hook: is_ksu_transition found)
    else
      $(info -- You lost is_ksu_transition hook in your kernel)
      $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
      $(error You should integrate $(REPO_NAME) in your kernel.)
    endif
  endif
endif

# Keep a new line here!! Because someone may append config
